env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

Tests_task:
  matrix:
    freebsd_instance:
      image_family: freebsd-14-2
    freebsd_instance:
      image_family: freebsd-13-4
  prepare_script:
  - cd tests && sh prepare.sh
  test_script:
  - cd tests && env RUN_TESTS="unit integration system" sh ./run.sh
