name: Tests

on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: sudo apt-get install -y zfsutils-linux
      - name: Prepare ZFS environment
        run: cd tests && sudo sh prepare.sh
      - name: Run tests
        run: cd tests && sudo env RUN_TESTS="unit integration" sh ./run.sh
